version: '{build}'

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of io.js
  - ps: Install-Product node '0.10'
  - npm -g install npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - node --version
  - npm --version
  - npm install

test_script:
  - npm test
